openapi: '3.0.1'
info:
  version: 0.0.1
  title: 'FilesFromYou'

servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile

paths:
  /client/{clientId}/system:
    post:
      summary: Saves client system information
      description: This endpoint saves system information of client
      operationId: saveSystemInformation
      parameters:
        - in: path
          name: clientId
          schema:
            type: integer
          required: true
          description: Client identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SystemInfo'
      responses:
        "201":
          description: Saved successfully!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "400":
          description: Invalid JSON!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
  /client/{clientId}/logs:
    post:
      summary: Uploads client log file
      description: This endpoint uploads log file
      operationId: uploadLogFile
      parameters:
        - in: path
          name: clientId
          schema:
            type: integer
          required: true
          description: Client identifier
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: Uploaded successfully!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "400":
          description: Invalid JSON!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "422":
          description: Any of the fields are not parsable!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

components:
  schemas:
    Response:
      description: This is the message returns to the user
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    SystemInfo:
      description: This is the dto to store system info of client
      type: object
      properties:
        id:
          type: string
        clientId:
          type: string
        timestamp:
          type: string
        host:
          type: object
          properties:
            name:
              type: string
            cpu:
              type: object
              properties:
                name:
                  type: string
                cores:
                  type: integer
            ip:
              type: array
              items:
                type: string
            architecture:
              type: string
            os:
              type: object
              properties:
                build:
                  type: string
                platform:
                  type: string
                version:
                  type: string
                name:
                  type: string
                kernel:
                  type: string
